export const events = Object.freeze({
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  TOGGLE_TODO_COMPLETION: 'TOGGLE_TODO_COMPLETION',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  SET_LOCALE: 'SET_LOCALE',
  // Persist effect using redux logic
  PERSIST_TODO: 'PERSIST_TODO',
  PERSIST_SUCCESS: 'PERSIST_SUCCESS',
  PERSIST_FAILURE: 'PERSIST_FAILURE',
  PERSIST_CANCELED: 'PERSIST_CANCELED',
  // Routing using redux first routing
  PUSH: 'ROUTER/PUSH',
  REPLACE: 'ROUTER/REPLACE',
  GO: 'ROUTER/GO',
  GO_BACK: 'ROUTER/GO_BACK',
  GO_FORWARD: 'ROUTER/GO_FORWARD',
  LOCATION_CHANGE: 'ROUTER/LOCATION_CHANGE'
});
