export const events = Object.freeze({
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  COMPLETE_ALL_TODOS: 'COMPLETE_ALL_TODOS',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  SET_LOCALE: 'SET_LOCALE',
});
